import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { authOptions } from "@/lib/auth";
import db from "@/lib/db";
import { getServerSession } from "next-auth";
import { User } from "@/types/user";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nextjs with Prisma and NextAuth",
  description: "Generated by create next app",
  icons: {
    icon: "/nextjs-fill.svg",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const ses = session?.user;
  const user = (await db.user.current()) as User;

  return (
    <html lang="en" className={`min-h-screen ${inter.className}`}>
      <body className="bg-zinc-50 min-h-screen max-w-4xl mx-auto w-full font-sans text-zinc-700">
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <Navbar user={user} />
        <main className="min-h-[70vh] my-5 bg-white rounded-md shadow p-5">
          {children}
        </main>
      </body>
    </html>
  );
}
