import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nextjs with Prisma and NextAuth",
  description: "Generated by create next app",
  icons: {
    icon: "/nextjs-fill.svg",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen">
      <body className="bg-zinc-50 min-h-screen max-w-4xl mx-auto w-full font-sans text-zinc-700">
        <NextTopLoader
          color="#3b82f6"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
          shadow="0 0 10px #3b82f6,0 0 5px #3b82f6"
        />
        <Navbar />
        <main className="min-h-[70vh] my-5 bg-white rounded-md shadow p-5">
          {children}
        </main>
      </body>
    </html>
  );
}
